[build]
  # Build command for static site
  command = "echo 'Static HTML site - no build needed'"
  # Directory to deploy
  publish = "."

[build.environment]
  # Environment variables if needed later
  NODE_VERSION = "18"

[[headers]]
  # Security headers for better SEO and security
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for better SEO (if needed later)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Form handling (for future contact forms)
# [[redirects]]
#   from = "/success"
#   to = "/thank-you"
#   status = 200